- load-test/src/gatling/resources/conf/application.conf
- load-test/src/gatling/scala/com/vivareal/search/config/SearchAPIv2Feeder.scala
- load-test/src/gatling/scala/com/vivareal/search/repository/SearchAPIv2Repository.scala
- load-test/src/gatling/scala/com/vivareal/search/simulation/SearchAPIv2Simulation.scala
Closes https://github.com/VivaReal/squad-search/issues/708
> Add load tests to idsIn

- load-test/src/gatling/scala/com/vivareal/search/repository/SearchAPIv2Repository.scala
- src/main/java/com/vivareal/search/api/adapter/SortQueryAdapter.java
- src/test/java/com/vivareal/search/api/adapter/SortQueryAdapterTest.java
> Remove sort by default when client input an empty sort on request

- src/main/java/com/vivareal/search/api/adapter/ElasticsearchQueryAdapter.java
Please ignore white spaces to view the changes of this code (add `w=1` on github)
> Create MM error message only when needed and some 'arrow code' changes

- src/main/java/com/vivareal/search/api/controller/stream/ElasticSearchStream.java
Closes https://github.com/VivaReal/squad-search/issues/712
> Fixing default values for size and sort in stream endpoint

- Makefile
- src/main/java/com/vivareal/search/api/configuration/ApiBeans.java
- src/main/resources/application.properties
> Fixing number of processors

- README.md
- src/main/java/com/vivareal/search/api/SearchAPI.java
- src/main/java/com/vivareal/search/api/controller/SearchController.java
- src/main/java/com/vivareal/search/api/controller/error/ExceptionController.java
- src/main/java/com/vivareal/search/api/controller/error/ExceptionHandler.java
Closes https://github.com/VivaReal/squad-search/issues/713
> Fix Hystrix fallback

- build.gradle
- src/main/resources/logback-spring.xml
Closes https://github.com/VivaReal/squad-search/issues/716
> External dependencies log level

- src/main/java/com/vivareal/search/api/adapter/ElasticsearchQueryAdapter.java
See https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-get.html#realtime
> Do not force refresh (realtime search) on every getByID

- load-test/build.gradle
> Upgrading gatling version for load test project

- src/main/java/com/vivareal/search/api/controller/SearchController.java
https://github.com/Netflix/Hystrix/wiki/Configuration#executionisolationsemaphoremaxconcurrentrequests
> Increase hystrix semaphore concurrent request

- deploy/variables/prod.yml
- deploy/variables/us-east-1/prod.yml
> Updating EC2 Instance type

- deploy/variables/us-east-1/prod.yml
> Updating AMI in order to support c5 instance type

- src/main/java/com/vivareal/search/api/configuration/NewRelicTransactionFilter.java
- src/main/java/com/vivareal/search/api/service/SearchService.java
Relates to https://github.com/VivaReal/squad-search/issues/464
> Yet another way of ignoring NewRelic transactions

- build.gradle
- load-test/build.gradle
- load-test/deploy/k8s/overrides.json.tmpl
- load-test/src/gatling/resources/conf/application.conf
- load-test/src/gatling/resources/conf/scenarios.conf
- load-test/src/gatling/scala/com/vivareal/search/config/SearchAPIv2Feeder.scala
- load-test/src/gatling/scala/com/vivareal/search/context/SourceFeeder.scala
- load-test/src/gatling/scala/com/vivareal/search/context/SourceFeederFilter.scala
- load-test/src/gatling/scala/com/vivareal/search/context/SourceFeederIds.scala
- load-test/src/gatling/scala/com/vivareal/search/context/SourceFeederIdsIn.scala
- load-test/src/gatling/scala/com/vivareal/search/repository/SearchAPIv2Repository.scala
- load-test/src/gatling/scala/com/vivareal/search/simulation/SearchAPIv2Simulation.scala
- settings.gradle
> Add dynamic load tests to RP

- src/main/resources/logback-spring.xml
Closes https://github.com/VivaReal/squad-search/issues/717
> Adding cluster and server to logs

- Makefile
- load-test/src/gatling/resources/conf/application.conf
- load-test/src/gatling/scala/com/vivareal/search/repository/SearchAPIv2Repository.scala
- src/main/java/com/vivareal/search/api/adapter/ElasticsearchQueryAdapter.java
- src/test/java/com/vivareal/search/api/adapter/ElasticsearchQueryAdapterTest.java
Closes https://github.com/VivaReal/squad-search/issues/695
> Change query context used by MUST to filter context using FILTER

- Makefile
Closes https://github.com/VivaReal/squad-search/issues/726
Make possible that load-test data do not get mixed with production info.
> Disable NewRelic agent by default

- load-test/src/gatling/resources/conf/application.conf
- load-test/src/gatling/resources/conf/scenarios.conf
- load-test/src/gatling/scala/com/vivareal/search/context/SourceFeederFilter.scala
- load-test/src/gatling/scala/com/vivareal/search/context/SourceFeederIdsIn.scala
- load-test/src/gatling/scala/com/vivareal/search/simulation/SearchAPIv2Simulation.scala
- load-test/src/gatling/scala/com/vivareal/search/util/PaginationUtils.scala
> Add random pagination on load-tests

- src/integration-test/java/com/vivareal/search/api/itest/SearchApiIntegrationTest.java
- src/integration-test/java/com/vivareal/search/api/itest/scenarios/NestedIntegrationTest.java
- src/integration-test/java/com/vivareal/search/api/itest/scenarios/SearchIntegrationTest.java
- src/main/java/com/vivareal/search/api/adapter/ElasticsearchQueryAdapter.java
- src/test/java/com/vivareal/search/api/adapter/ElasticsearchQueryAdapterTest.java
Closes https://github.com/VivaReal/squad-search/issues/725
> Fix bug on nested queries

- src/integration-test/java/com/vivareal/search/api/itest/scenarios/NestedIntegrationTest.java
- src/main/java/com/vivareal/search/api/adapter/ElasticsearchQueryAdapter.java
- src/test/java/com/vivareal/search/api/adapter/ElasticsearchQueryAdapterTest.java
Closes https://github.com/VivaReal/squad-search/issues/752
> Fix filter by nested type

- src/integration-test/java/com/vivareal/search/api/itest/scenarios/NestedIntegrationTest.java
- src/main/java/com/vivareal/search/api/adapter/ElasticsearchQueryAdapter.java
Closes https://github.com/VivaReal/squad-search/issues/757
> Fix bug from filter by nested from recursive queries

- src/integration-test/java/com/vivareal/search/api/itest/scenarios/QueryStringIntegrationTest.java
- src/main/java/com/vivareal/search/api/adapter/ElasticsearchQueryAdapter.java
- src/test/java/com/vivareal/search/api/adapter/ElasticsearchQueryAdapterTest.java
Closes https://github.com/VivaReal/squad-search/issues/759
> Fix querystring query moving from should to filter

- src/integration-test/java/com/vivareal/search/api/itest/scenarios/SearchIntegrationTest.java
- src/main/java/com/vivareal/search/api/controller/stream/ResponseStream.java
- src/test/java/com/vivareal/search/api/controller/stream/ResponseStreamTest.java
Closes https://github.com/VivaReal/squad-search/issues/762
> Adding blank line when stream is finished

- src/jmh/java/com/vivareal/search/api/benchmark/ElasticsearchQueryAdapterBenchmark.java
- src/main/java/com/vivareal/search/api/adapter/ElasticsearchQueryAdapter.java
- src/main/java/com/vivareal/search/api/adapter/FilterQueryAdapter.java
- src/main/java/com/vivareal/search/api/adapter/SortQueryAdapter.java
- src/main/java/com/vivareal/search/api/model/query/Sort.java
- src/test/java/com/vivareal/search/api/adapter/ElasticsearchQueryAdapterTest.java
- src/test/java/com/vivareal/search/api/adapter/FilterQueryAdapterTest.java
- src/test/java/com/vivareal/search/api/adapter/SortQueryAdapterTest.java
Closes https://github.com/VivaReal/squad-search/issues/763
> Reusing filterQueryAdapter to build sortFilter

- src/integration-test/java/com/vivareal/search/api/itest/SearchApiIntegrationTest.java
- src/integration-test/java/com/vivareal/search/api/itest/configuration/data/StandardDatasetAsserts.java
- src/integration-test/java/com/vivareal/search/api/itest/configuration/data/TestData.java
- src/integration-test/java/com/vivareal/search/api/itest/configuration/es/ESIndexHandler.java
- src/integration-test/java/com/vivareal/search/api/itest/configuration/es/ESIntegrationTestSetup.java
- src/integration-test/java/com/vivareal/search/api/itest/scenarios/NestedIntegrationTest.java
- src/integration-test/java/com/vivareal/search/api/itest/scenarios/QueryTimeoutIntegrationTest.java
- src/integration-test/java/com/vivareal/search/api/itest/scenarios/SearchIntegrationTest.java
- src/integration-test/java/com/vivareal/search/api/itest/scenarios/SortIntegrationTest.java
- src/integration-test/resources/es/bootstrap.json
Closes https://github.com/VivaReal/squad-search/issues/755
> Integration tests for nested arrays

- src/main/java/com/vivareal/search/api/model/search/Pageable.java
- src/test/java/com/vivareal/search/api/model/SearchApiRequestTest.java
Closes https://github.com/VivaReal/squad-search/issues/775
> Check for pagination window (from + size) too large

- src/main/java/com/vivareal/search/api/adapter/QueryStringAdapter.java
- src/test/java/com/vivareal/search/api/adapter/ElasticsearchQueryAdapterTest.java
- src/test/java/com/vivareal/search/api/adapter/QueryStringAdapterTest.java
Closes https://github.com/VivaReal/squad-search/issues/777
> Migrating Query String to Multi Match Query

- src/main/java/com/vivareal/search/api/model/SearchApiIterator.java
- src/main/java/com/vivareal/search/api/service/SearchService.java
Closes https://github.com/VivaReal/squad-search/issues/780
> Checking for failed shards in ES response

- src/main/java/com/vivareal/search/api/controller/error/ExceptionHandler.java
Closes https://github.com/VivaReal/squad-search/issues/790
> Always log stack so that sentry can group similar issues

- src/main/resources/logback-spring.xml
grupozap/squad-search-ranking#1327
> Updating deprecated Sentry DSN
